name: twst
favicon: null
layout_spectrum: 0.4534124368801713
typography_spectrum: 0.8952406051103026
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.17850198433734477
  lightness: 0.5528789174277335
  saturation: 0.32593722618184984
  rhythmicContrast: 0.6291506949346513
purpose: []
